### PR TITLE
Stage 2

### PR DESCRIPTION
**Pull request by mariawright05**
Since there is no connection to an api yet, you can find the initial state of the user in `context>auth>AuthState.js.` The functionality works if you logout from this user. Registering or signing in using the form will revert back to this default user, no matter what you submit.

In the same way, there are 2 default cards set to "saved" in `context>news>NewsState.js`. Until there is an api connection, these show up initially as saved, even when not logged in. Aside from this the saved buttons do work when logged in, and show an error when not.

### CODE REVIEW

**Comment by ImaliaNsk** [comment]
Hello Maria!
Good job! Some corrections need to be made, but on the whole, the project is very impressive! I hope that the issues will be easy to fix!

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* A horizontal scroll on desktop resolutions: https://prnt.sc/12dx0ei
* The "search" button is on top of the popup window: https://prnt.sc/12dx5w9, the same issue with "Registration completed" popup
* The navigation menu on `saved-news`: https://prnt.sc/12dxaes

- [ ]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.

* "Nothing found" block isn't coded
* The links in the footer should lead to the correspondent external resources and be opened in new tabs

- [ ]  The layout is responsive and displays correctly at all intermediate resolutions.

* The images in cards lose their proportions on intermediate resolutions: https://prnt.sc/12dxbpx https://prnt.sc/12dxcgc

- [ ]  There are no validation errors.

https://prnt.sc/12dxdwk
div can't be a child of ul. <li> can't be a child of div: https://prnt.sc/12dxisx. Please correct all similar cases.

- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [ ]  A components folder with JS and CSS files for the components.
	* A redundant folder in components: https://prnt.sc/12dxmbq
	* No JS file for pageContainer. Please remove the folder if it's not needed.
	* If these are different components they need different folders, and each of them needs its own js and css file: https://prnt.sc/12dxppr.
	- [x]  A fonts folder.

### Best Practices
- [ ]  Classes are named according to BEM specifications.
* Shouldn't be a modifier: https://prnt.sc/12dxsh2, it's an element
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [ ]  Form elements should be highlighted when focused.
- [ ]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 44

**Comment by mariawright05** [comment]
I believe I have fixed all of the issues. However, I could not replicate the horizontal scroll in any browser.

**Comment by ImaliaNsk** [comment]
Great job, almost everything is fixed.

# Project review summary:
### Performance Criteria
- [ ]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.

* A horizontal scroll on desktop resolutions: https://prnt.sc/12dx0ei is still there. I can make an assumption why you don't see it: most probably you have a Mac, it hides the scrollbars, you can change your preferencies to show scrollbars. To be more specific, the scroll is caused by your `author` section.
* Horizontal scroll on mobile screen: https://prnt.sc/12kiy2d

- [ ]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.

* "Nothing found" block can't be checked, please let me know how I can check the layout in the browser, I can see you've added the code for it, but can't find it connected to the page logic.

- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [x]  Classes are named according to BEM specifications.
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 72

**Comment by mariawright05** [comment]
You were right about being on a Mac. I fixed the horizontal scrollbar issue. I also set up simple logic to randomly display the Preloader or the NothingFound block before the card list appears. It's a temporary solution, but you will at least be able to see the block.

**Comment by ImaliaNsk** [comment]
Hi Maria! All perfect now, awesome work! The project is accepted, and I wish you good luck on the next stage!

# Project review summary:
### Performance Criteria
- [x]  The project is adapted for different screen resolutions and matches the designs for these resolutions. There is no horizontal scrolling on resolutions of 320px and up. The scrollbar can't be hidden using the overflow: hidden declaration.
- [x]  All the blocks from the brief have been coded. Navigation between pages and links to external resources are working correctly: there are no broken links or links leading to an anchor on the page and external links open in a new tab.
- [x]  The layout is responsive and displays correctly at all intermediate resolutions.
- [x]  There are no validation errors.
- [x]  Semantic HTML is used, meaning that semantic tags are used. All elements are used correctly (e.g. a paragraph must be a paragraph, a list must be a list). The DOM tree structure doesn't consist only of <div> containers.
- [x]  The correct approach is chosen for positioning elements, and is described using the correct syntax. For example, when positioning an element absolutely, its parent block is relatively positioned.
- [x]  flex or grid layout are used to arrange elements.
- [x]  Infrastructural project files are created using CRA.
- [x]  The popup windows have opening and closing functionality implemented.
- The markup has been converted into JSX:
	- [x]  The markup is included within parentheses ( ).
	- [x]  The markup has been moved into the corresponding components.
- Your project contains:
	- [x]  An images folder
	- [x]  A components folder with JS and CSS files for the components.
	- [x]  A fonts folder.

### Best Practices
- [x]  Classes are named according to BEM specifications.
- [x]  Buttons, input fields, and links are implemented in all of the states specified in the design.
- [x]  The design reuses components wherever possible.
- [x]  Fonts are connected using @font-face.
- [x]  The use of reset.css is prohibited.
- [x]  Form elements should be highlighted when focused.
- [x]  The form must have placeholders, and required fields should be validated.

### Recommendations
- [x]  Images have an alt attribute containing appropriate values.
- [x]  System fonts are connected as alternatives to each of your fonts.
- [x]  Raster and vector images have been optimized.

## Number of points: 100

**Pull request merged**
